### ISSUE TITLE
Assigning the user defined key "1" to an input on a template cause application to crash and close

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/traveler#6]
traveler-app/model/form.js:71
        userkey = userkey.trim();
                          ^

TypeError: userkey.trim is not a function
    at model.<anonymous> (traveler-app/model/form.js:71:27)
    at _next (traveler-app/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (traveler-app/node_modules/hooks-fixed/hooks.js:186:18)
    at model.fn (traveler-app/node_modules/mongoose/lib/schema.js:251:9)
    at _next (traveler-app/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (traveler-app/node_modules/hooks-fixed/hooks.js:186:18)
    at traveler-app/node_modules/mongoose/lib/schema.js:235:13
    at complete (traveler-app/node_modules/mongoose/lib/document.js:1170:5)
    at traveler-app/node_modules/mongoose/lib/document.js:1198:20
    at SchemaArray.SchemaType.doValidate (traveler-app/node_modules/mongoose/lib/schematype.js:667:12)
    at traveler-app/node_modules/mongoose/lib/document.js:1194:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by dongliu** [comment]
reproduced. I assume the cheerio parse the data-userkey to a number somehow. will fix soon.

**Comment by dongliu** [comment]
confirmed that the cheerio .data() caused that, fix with .attr()
